export const plusSizeList = [
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s1-1.jpg?v=1603764629',
    altText: 'Drawstring Hooded Sweater',
    title: 'Drawstring Hooded Sweater',
    color: '+2 colors',
    price: '$189',
    handle: '/products/drawstring-hooded-sweater-old-rose',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s1-2.jpg?v=1603764630',
    altText: 'Rib and Pointelle Cashmere Sweater',
    title: 'Rib and Pointelle Cashmere Sweater',
    color: '+2 colors',
    price: '$169',
    handle: '/products/rib-and-pointelle-cashmere-sweater-toasted-almond',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s1-3.jpg?v=1603764629',
    altText: 'Side Button Sweater',
    title: 'Side Button Sweater',
    color: '+2 colors',
    price: '$139',
    handle: '/products/side-button-sweater-old-rose',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s1-4.jpg?v=1603764628',
    altText: 'Drawstring Side Sweater',
    title: 'Drawstring Side Sweater',
    color: '+2 colors',
    price: '$129',
    handle: '/products/drawstring-side-sweater-toasted-almond',
    style: ' ',
  },

  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s2-1.jpg?v=1603764630',
    altText: 'Contrast Tipped 3 Piece Set',
    title: 'Contrast Tipped 3 Piece Set',
    color: ' ',
    price: '$109',
    handle: '/products/contrast-tipped-3-piece-set-toasted-almond',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s2-2.jpg?v=1603764629',
    altText: 'Button Back Sweater',
    title: 'Button Back Sweater',
    color: '+1 colors',
    price: '$139',
    handle: '/',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s2-3.jpg?v=1603764630',
    altText: 'V-Neck Midi Dress',
    title: 'V-Neck Midi Dress',
    color: '+2 colors',
    price: '$169',
    handle: '/products/v-neck-midi-dress-toasted-almond',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s2-4.jpg?v=1603764630',
    altText: 'Thick Cashmere Tank',
    title: 'Thick Cashmere Tank',
    color: '+2 colors',
    price: '$129',
    handle: '/products/thick-cashmere-tank-toasted-almond',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s3-1.jpg?v=1603764630',
    altText: 'Midi Skirt With Side Slits',
    title: 'Midi Skirt With Side Slits',
    color: '+4 colors',
    price: '$149',
    handle: '/products/midi-skirt-with-side-slits-toasted-almond',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s3-2.jpg?v=1603764630',
    altText: 'Midi Skirt With Side Slits',
    title: 'Midi Skirt With Side Slits',
    color: '+4 colors',
    price: '$149',
    handle: '/products/midi-skirt-with-side-slits-decadent-chocolate',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s3-3.jpg?v=1603764629',
    altText: 'Silk Cashmere Relaxed Fit Cardigan',
    title: 'Silk Cashmere Relaxed Fit Cardigan',
    color: '+5 colors',
    price: '$209',
    handle: '/products/silk-cashmere-relaxed-fit-cardigan-beige',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s3-4.jpg?v=1603764630',
    altText: 'Silk Cashmere Relaxed Fit Boat-Neck Sweater',
    title: 'Silk Cashmere Relaxed Fit Boat-Neck Sweater',
    color: '+6 colors',
    price: '$179',
    handle: '/products/silk-cashmere-relaxed-fit-c-neck-sweater-blue',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s4-1.jpg?v=1603764630',
    altText: 'Silk Cashmere Relaxed Fit Boat-Neck Sweater',
    title: 'Silk Cashmere Relaxed Fit Boat-Neck Sweater',
    color: '+6 colors',
    price: '$179',
    handle: '/products/silk-cashmere-relaxed-fit-c-neck-sweater-light-gray',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s4-2.jpg?v=1603764630',
    altText: 'Silk Cashmere Relaxed Fit Cardigan',
    title: 'Silk Cashmere Relaxed Fit Cardigan',
    color: '+5 colors',
    price: '$209',
    handle: '/products/silk-cashmere-relaxed-fit-cardigan-light-gray',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s4-3.jpg?v=1603764629',
    altText: 'Silk Cashmere Relaxed Fit Boat-Neck Sweater',
    title: 'Silk Cashmere Relaxed Fit Boat-Neck Sweater',
    color: '+6 colors',
    price: '$179',
    handle: '/products/silk-cashmere-relaxed-fit-c-neck-sweater-slate',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s4-4.jpg?v=1603764630',
    altText: 'Silk Cashmere Relaxed Fit Boat-Neck Sweater',
    title: 'Silk Cashmere Relaxed Fit Boat-Neck Sweater',
    color: '+6 colors',
    price: '$179',
    handle: '/products/silk-cashmere-relaxed-fit-c-neck-sweater-dusty-blue',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s5-1.jpg?v=1603764628',
    altText: 'Silk Cashmere Relaxed Fit Boat-Neck Sweater',
    title: 'Silk Cashmere Relaxed Fit Boat-Neck Sweater',
    color: '+6 colors',
    price: '$179',
    handle: '/products/silk-cashmere-relaxed-fit-c-neck-sweater-powder-pink',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s5-2.jpg?v=1603764629',
    altText: 'Silk Cashmere Relaxed Fit Cardigan',
    title: 'Silk Cashmere Relaxed Fit Cardigan',
    color: '+5 colors',
    price: '$209',
    handle: '/products/silk-cashmere-relaxed-fit-cardigan-powder-pink',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s5-3.jpg?v=1603764630',
    altText: 'Silk Cashmere Short-Sleeved C-Neck Top',
    title: 'Silk Cashmere Short-Sleeved C-Neck Top',
    color: '+2 colors',
    price: '$129',
    handle: '/products/silk-cashmere-short-sleeved-c-neck-top-orchid-bloom',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s5-4.jpg?v=1603764630',
    altText: 'High Neck With Cord',
    title: 'High Neck With Cord',
    color: '+4 colors',
    price: '$179',
    handle: '/products/high-neck-with-cord-pale-mauve',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s6-1.jpg?v=1603764630',
    altText: 'Button Back Sweater',
    title: 'Button Back Sweater',
    color: '+1 colors',
    price: '$139',
    handle: '/products/button-back-sweater-black-plum',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s6-2.jpg?v=1603764628',
    altText: 'High Neck Sweater',
    title: 'High Neck Sweater',
    color: '+2 colors',
    price: '$99',
    handle: '/products/high-neck-sweater-black-plum',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s6-3.jpg?v=1603764627',
    altText: 'V-Neck Midi Dress',
    title: 'V-Neck Midi Dress',
    color: '+2 colors',
    price: '$169',
    handle: '/products/v-neck-midi-dress-decadent-chocolate',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s6-4.jpg?v=1603764629',
    altText: 'Loose Turtle Neck Sweater',
    title: 'Loose Turtle Neck Sweater',
    color: '+1 colors',
    price: '$199',
    handle: '/products/loose-turtle-neck-sweater-taupe',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s7-1.jpg?v=1603764630',
    altText: 'Drawstring Hooded Sweater',
    title: 'Drawstring Hooded Sweater',
    color: '+2 colors',
    price: '$189',
    handle: '/products/drawstring-hooded-sweater-blue-iris',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s7-2.jpg?v=1603764630',
    altText: 'High Neck Sweater',
    title: 'High Neck Sweater',
    color: '+2 colors',
    price: '$99',
    handle: '/products/high-neck-sweater-cowhide',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s7-3.jpg?v=1603764628',
    altText: 'Thick Cashmere Tank',
    title: 'Thick Cashmere Tank',
    color: '+2 colors',
    price: '$129',
    handle: '/products/thick-cashmere-tank-cowhide',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s7-4.jpg?v=1603764629',
    altText: 'Cashmere Poncho Sweater',
    title: 'Cashmere Poncho Sweater',
    color: '+2 colors',
    price: '$169',
    handle: '/products/cashmere-poncho-sweater-cowhide',
    style: ' ',
  },
  {
    image: 'https://cdn.shopify.com/s/files/1/0249/6551/3262/files/s8-1.jpg?v=1603764628',
    altText: 'Silk Cashmere Relaxed Fit Boat-Neck Sweater',
    title: 'Silk Cashmere Relaxed Fit Boat-Neck Sweater',
    color: '+6 colors',
    price: '$179',
    handle: '/products/silk-cashmere-relaxed-fit-c-neck-sweater-black',
    style: ' ',
  },
];
