export const initialStateFilter = {
  colorFilters: [
    {
      label: 'Black',
      imgUrl: 'https://cdn.shopify.com/s/files/1/0098/6044/8292/files/color-black.png',
      colors: ['black'],
      checked: false,
      checkColor: 'white',
    },
    {
      label: 'Brown',
      imgUrl: 'https://cdn.shopify.com/s/files/1/0098/6044/8292/files/color-brown.png',
      colors: [
        `Brown`,
        `caramel cream`,
        `ginger root`,
        `Light camel`,
        `toasted almond`,
        `Sheepskin`,
        `Roebuck`,
        `Tawny brown`,
        `Almond`,
        `Pumpkin Spice`,
        `Camel`,
        `Mocha`,
        `leather brown`,
        `Sequoia`,
        `twilight mauve`,
        `Deep taupe`,
        `andorra`,
        `Shopping bag`,
        `decadent chocolate`,
        `Java`,
        `Chocolate brown`,
        `Coffee bean`,
        'molé',
        'sugar almond',
        'cabernet',
      ],
      checked: false,
      checkColor: 'white',
    },
    {
      label: 'Marine',
      imgUrl: 'https://cdn.shopify.com/s/files/1/0098/6044/8292/files/color-marine.png',
      colors: [
        `Marine`,
        `Arctic ice`,
        `Gray Dawn`,
        `Thistle`,
        `Brunnera blue`,
        `Dusty lavender`,
        `Blue iris`,
        `Surf the web`,
        `blueprint`,
        `Sodalite blue`,
        `Nightshadow blue`,
        `Crown blue`,
        `Peacoat`,
        `Deep well`,
        `Midnight`,
        `Illusion blue`,
        `Sky way`,
        `Light blue`,
        `chambray blue`,
        `Airy blue`,
        `Blue`,
        `Blue granite`,
        `purple impression`,
        `English manor`,
        `Ultra marine`,
        `Bijou blue`,
        `Navy peony`,
        `black iris`,
        `Navy`,

        `Baby blue`,
        `Blue glass`,
        `canal blue`,
        `delphinium blue`,
        `dusty blue`,
        `Blue heaven`,
        `Coronet blue`,
        `blithe`,
        `hawaiian ocean`,
        `Caribbean sea`,
        `mosaic blue`,
        `Peacock`,
        `Moroccan blue`,
        `Ensign blue`,
        `Majolica blue`,
        `Ebony`,
        `Eclipse`,
        'winter sky',
        'navy blazer',
        'starlight blue',
        'twilight blue',
        'copen blue',
        'dress blues',
        'poseidon',
      ],
      checked: false,
      checkColor: 'white',
    },
    {
      label: 'Green',
      imgUrl: 'https://cdn.shopify.com/s/files/1/0098/6044/8292/files/color-green.png',
      colors: [
        `Green`,
        `Whispering Blue`,
        `Clearly Aqua`,
        `Pale aqua`,
        `Gray mist`,
        `Jade green`,
        'opal',
        'cypress',
        `Arctic blue`,
        `Abyss`,
        `slate`,
        `Dusty green`,
        `deep lake`,
        `Teal green`,
        `shady glade`,
        `Atlantic deep`,
        `Agave green`,
        `Capulet olive`,
        `sea spray`,
        `bronze green`,
        `Trekking green`,
        `Jane bug`,
        `Sea moss`,
        `Dark green`,
        `greener pastures`,
        `Kombu green`,
        `Dark olive`,
        'teal',
        'vetiver',
        'loden frost',
      ],
      checked: false,
      checkColor: 'white',
    },
    {
      label: 'Grey',
      imgUrl: 'https://cdn.shopify.com/s/files/1/0098/6044/8292/files/color-grey.png',
      colors: [
        `Grey`,
        `Antarctica`,
        `Micro chip`,
        `White gray`,
        `Light gray`,
        `Harbor Mist`,
        `Paloma`,
        `tradewinds`,
        `Sharkskin`,
        `Stone gray`,
        `Neutral gray`,
        `Dim gray`,
        `Charcoal`,
        `Shale`,
        'vapor blue',
        'gray morn',
        'storm front',
      ],
      checked: false,
      checkColor: 'black',
    },
    {
      label: 'Red',
      imgUrl: 'https://cdn.shopify.com/s/files/1/0098/6044/8292/files/color-reddish.png',
      colors: [
        `Red`,
        `Salmon`,

        `Shrimp`,
        `Burnt Coral`,
        `Fusion Coral`,
        `Coral`,
        `tangerine tango`,
        `Shell pink`,
        `Cayenne`,

        `Spicy orange`,
        `Scarlet`,
        `Fiery red`,
        `Red`,

        `racing red`,
        `ribbon red`,
        `rose red`,
        `barberry`,
        `Haute red`,

        `Earth red`,
        `Burnt brick`,
        `Tandori spice`,
        `red clay`,
        `Burnt ochre`,
        `Burnt henna`,
        `Crushed berry`,
        `Bordeaux`,

        `Rhododendron`,
        `Cabernet`,

        `Madder brown`,
        `cowhide`,
        `sassafras`,
        `bitter chocolate`,
        `black plum`,
        'aurora red',
        'chili',
      ],
      checked: false,
      checkColor: 'black',
    },
    {
      label: 'Pink',
      imgUrl: 'https://cdn.shopify.com/s/files/1/0098/6044/8292/files/color-pink.png',
      colors: [
        `Pink`,
        `Rosewater`,
        `Blossom pink`,
        `pearl blush`,
        `Dusty pink`,
        `Blush`,
        `Pale lilac`,
        `Mauve Chalk`,
        `Rose smoke`,
        `Adobe rose`,
        `Wood rose`,
        `lilas`,

        `Ash rose`,

        `Old rose`,
        `pale mauve`,
        `Grape shake`,
        `Rose brown`,
        `Dark purple`,
        `Rum raisin`,
        `Fuchsia rose`,
        `bright rose`,
        `Raspberry radiance`,
        `Beaujolais`,
        `Tibetan red`,
        `Paradise pink`,
        `Powder pink`,

        `Orchid ice`,
        'cherries jubilee',
        'pale dogwood',
        'foxglove',
        `Orchid hush`,
        `orchid bloom`,
        `Orchid Bouquet`,
        `Lavender frost`,
        `Sandstone`,
        `Lavender gray`,
        `grape jam`,
        `Sweet grape`,
        `Plum perfect`,
        `Bellflower`,
        'bubblegum',
        'winetasting',
        'peach blossom',
        'chalk violet',
        'puple gumdrop',
        'heirloom lilac',
        'deep periwinkle',
        'almond blossom',
        'zephyr',
      ],
      checked: false,
      checkColor: 'white',
    },
    {
      label: 'Yellow',
      imgUrl: 'https://cdn.shopify.com/s/files/1/0098/6044/8292/files/color-lemon.png',
      colors: [
        `Yellow`,
        `French Vanilla`,
        `pale banana`,
        `golden haze`,
        `Yellow`,
        `daffodil`,
        `Yolk yellow`,
        `Mustard`,

        `citronelle`,
        `Mustard gold`,
        `peach nougat`,
        `Sun orange`,
        `Red orange`,
        `Nasturtium`,
        `Tigerlily`,
        `apricot`,
        'solar power',
        'yellow iris',
      ],
      checked: false,
      checkColor: 'white',
    },
    {
      label: 'Taupe',
      imgUrl: 'https://cdn.shopify.com/s/files/1/0098/6044/8292/files/color-sand.png',
      colors: [
        `Taupe`,
        `Beige`,

        `Whitecap Gray`,
        `Parchment`,
        `Tapioca`,
        `Creme brulee`,
        `sandshell`,
        `Wintermood`,
        `Fog`,
        `Warm grey`,

        `light taupe`,
        `Feather gray`,
        `Plaza taupe`,
        `Taupe`,

        `Satellite`,
        `Cocoa`,

        `Turkish coffee`,
        `buttercream`,
        'shitake',
        'otter',
        'falcon',
        'nomad',
        'almond milk',
      ],
      checked: false,
      checkColor: 'white',
    },
    {
      label: 'White',
      imgUrl: 'https://cdn.shopify.com/s/files/1/0098/6044/8292/files/color-cream.png',
      colors: [`White`, `Snow white`, `Off white`, `Tofu`, `Ivory white`, `Whisper white`],
      checked: false,
      checkColor: 'black',
    },

    {
      label: 'Multi Color',
      focus: 'tag',
      imgUrl: 'https://cdn.shopify.com/s/files/1/1953/2845/files/multi-color.png?v=1597637857',
      tags: ['multicolor'],
      checked: false,
      checkColor: 'white',
    },
  ],
  sizeFilters: [
    {
      label: 'ONE SIZE',
      size: ['One Size'],
      checked: false,
      position: 1,
    },
    {
      label: '2XS',
      size: ['2XS'],
      checked: false,
      position: 2,
    },
    {
      label: 'XS',
      size: ['XS', '2XS - XS'],
      checked: false,
      position: 3,
    },
    {
      label: 'S',
      size: ['S', 'XS - S'],
      checked: false,
      position: 4,
    },
    {
      label: 'M',
      size: ['M', 'S - M'],
      checked: false,
      position: 5,
    },
    {
      label: 'L',
      size: ['L', 'M - L'],
      checked: false,
      position: 6,
    },
    {
      label: 'XL',
      size: ['XL', 'L - XL'],
      checked: false,
      position: 7,
    },
    {
      label: '2XL',
      size: ['2XL', 'XL - 2XL'],
      checked: false,
      position: 8,
    },
    {
      label: '3XL',
      size: ['3XL'],
      checked: false,
      position: 9,
    },
    {
      label: '4XL',
      size: ['4XL'],
      checked: false,
      position: 10,
    },
  ],
  categoriesFilters: [],
  sortFilters: [
    // {
    //   label: 'New',
    //   checked: false,
    //   id:"new"
    // },
    {
      label: 'Price Low - High',
      checked: false,
      id: 'price_asc',
    },
    {
      label: 'Price High - Low',
      checked: false,
      id: 'price_desc',
    },
  ],
  priceFilters: [
    {
      start: 0,
      end: 100,
      checked: false,
      label: '0:100',
    },
    {
      start: 100,
      end: 200,
      checked: false,
      label: '100:200',
    },
    {
      start: 200,
      end: 300,
      checked: false,
      label: '200:300',
    },
    {
      start: 300,
      // end: "",
      checked: false,
      label: '300:',
    },
  ],
  tagSplits: {
    collection: [
      {
        tag: 'organic',
        changing: {
          label: 'Organic Cashmere',
        },
      },
      {
        tag: 'silk',
        changing: {
          label: 'Cashmere Silk Blend',
        },
      },
      {
        tag: 'paintbox',
        changing: {
          label: 'Paintbox',
        },
      },
      {
        tag: 'winter spice',
        changing: {
          label: 'Winter Spice',
        },
      },
      {
        tag: 'trending',
        changing: {
          label: 'Trending',
        },
      },
      {
        tag: 'bestsellers',
        changing: {
          label: 'Best Seller',
        },
      },
    ],
    gender: [
      {
        tag: 'man',
        changing: {
          label: 'Men',
        },
      },
      {
        tag: 'women',
        changing: {
          label: 'Women',
        },
      },
    ],
    sale: [
      {
        tag: 'sale30',
        changing: {
          label: 'Sale 30%',
        },
        order: 1,
      },
      {
        tag: 'sale50',
        changing: {
          label: 'Sale 50%',
        },
        order: 2,
      },
    ],
  },
};

export function makeId(length) {
  var result = '';
  var characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
  var charactersLength = characters.length;
  for (var i = 0; i < length; i++) {
    result += characters.charAt(Math.floor(Math.random() * charactersLength));
  }
  return result;
}
